[FIX] web_form_orderedby: Fetch all fields before sorting
`orderedBy` was incorrectly set, that leads to client-side errors.

Example when sorting by product a long list (paged) of purchase order lines:
Error: While parsing modifiers for field product_id: for modifier "readonly": Unknown field state in domain