[FIX] mrp_traceability: Invalid value set by default context
The form context is set with a default value for state (default_state) but this key is propagated to `mail.tracking.email` that also contains a state field.

This will raise an error like:

2025-03-18 14:47:08,043 1706231 ERROR dec odoo.addons.mail.models.mail_mail: failed sending mail (id: 178939) due to Wrong value for mail.tracking.email.state: 'draft'
Traceback (most recent call last):
  File "/opt/odoo/14.0/odoo/addons/mail/models/mail_mail.py", line 315, in _send
    values = mail._send_prepare_values(partner=partner)
  File "/opt/odoo/14.0/odoo-addons/oca/social/mail_tracking/models/mail_mail.py", line 36, in _send_prepare_values
    tracking_email = self.env["mail.tracking.email"].sudo().create(vals)
[...]
  File "/opt/odoo/14.0/odoo/odoo/fields.py", line 2437, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for mail.tracking.email.state: 'draft'